@echo off
echo Installing Reminders Application dependencies...
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Installation complete!
echo You can now run the application with: python main.py
pause
